// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"database/sql"
)

type User struct {
	ID           int64
	CreatedAt    string
	UpdatedAt    string
	RealName     string
	Nickname     string
	Email        string
	ProfileImage sql.NullString
}
