// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: session.sql

package database

import (
	"context"
	"time"
)

const createSession = `-- name: CreateSession :one
insert into sessions (
    user_id,
    expires_at,
    created_at,
    updated_at
) values (
    ?,
    ?,
    ?,
    ?
) returning id
`

type CreateSessionParams struct {
	UserID    int64
	ExpiresAt time.Time
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createSession,
		arg.UserID,
		arg.ExpiresAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
