// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: users.sql

package database

import (
	"context"
)

const getUser = `-- name: GetUser :one
select id, created_at, updated_at, real_name, nickname, email, profile_image from users where id = ?
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RealName,
		&i.Nickname,
		&i.Email,
		&i.ProfileImage,
	)
	return i, err
}
